# Generated by Django 5.2 on 2025-05-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('BR', 'Basil'), ('US', 'AmeriEstados Unidoscan'), ('FR', 'França'), ('ES', 'Espanha'), ('IT', 'Italia'), ('JP', 'Japão'), ('CN', 'China'), ('KR', 'Corea do Sul'), ('IN', 'India'), ('DE', 'Alemanha'), ('RU', 'Rússia'), ('AU', 'Austrália'), ('CA', 'Canadá'), ('MX', 'México'), ('ZA', 'África do Sul'), ('AR', 'Argentina'), ('EG', 'Egito'), ('NG', 'Nigéria'), ('SE', 'Suécia'), ('NL', 'Países Baixos'), ('NO', 'Noruega'), ('FI', 'Finlândia'), ('DK', 'Dinamarca'), ('PL', 'Polônia'), ('CH', 'Suíça'), ('AT', 'Áustria'), ('BE', 'Bélgica'), ('PT', 'Portugal'), ('GR', 'Grécia'), ('HU', 'Hungria'), ('CZ', 'República Tcheca'), ('IE', 'Irlanda'), ('SK', 'Eslováquia'), ('SI', 'Eslovênia'), ('HR', 'Croácia'), ('BG', 'Bulgária'), ('RO', 'Romênia'), ('LV', 'Letônia'), ('LT', 'Lituânia'), ('EE', 'Estônia')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
