# Generated by Django 4.2.5 on 2025-07-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_alter_actor_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('BRAZIL', 'Bazil'), ('USA', 'Estados Unidos'), ('UK', 'Reino Unido'), ('FR', 'França'), ('ES', 'Espanha'), ('IT', 'Italia'), ('JP', 'Japão'), ('CN', 'China'), ('KR', 'Corea do Sul'), ('IN', 'India'), ('DE', 'Alemanha'), ('RU', 'Rússia'), ('AU', 'Austrália'), ('CA', 'Canadá'), ('MX', 'México'), ('ZA', 'África do Sul'), ('AR', 'Argentina'), ('EG', 'Egito'), ('NG', 'Nigéria'), ('SE', 'Suécia'), ('NL', 'Países Baixos'), ('NO', 'Noruega'), ('FI', 'Finlândia'), ('DK', 'Dinamarca'), ('PL', 'Polônia'), ('CH', 'Suíça'), ('AT', 'Áustria'), ('BE', 'Bélgica'), ('PT', 'Portugal'), ('GR', 'Grécia'), ('HU', 'Hungria'), ('CZ', 'República Tcheca'), ('IE', 'Irlanda'), ('SK', 'Eslováquia'), ('SI', 'Eslovênia'), ('HR', 'Croácia'), ('BG', 'Bulgária'), ('RO', 'Romênia'), ('LV', 'Letônia'), ('LT', 'Lituânia'), ('CL', 'Chile'), ('CO', 'Colômbia'), ('PE', 'Peru'), ('VE', 'Venezuela'), ('EC', 'Equador'), ('BO', 'Bolívia'), ('PY', 'Paraguai'), ('UY', 'Uruguai'), ('SV', 'El Salvador'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('NI', 'Nicarágua'), ('CR', 'Costa Rica'), ('PA', 'Panamá'), ('CU', 'Cuba'), ('DO', 'República Dominicana'), ('PR', 'Porto Rico'), ('EE', 'Estônia')], max_length=100, null=True),
        ),
    ]
